### ISSUE TITLE
Add Easy Peasy Support

### ISSUE THREAD

**Issue by dukesx** [the-write-grand-team/Write-Grand-CMS#3]
##### Redux
Redux forms an important and integral part of managing global state. its strict and compliant nature of syntax and data flow is the reason that is it THE library for state management. Adding is necessary as alot of data might need to be stored and managed globally by other components

##### Welcome Easy-Peasy
A Not so popular Redux based library , but a complete state management tool, borrowing all the best bits of libraries used for React state management. No boilerplate and easy to use , fast and compliant 

- [x] Add Easy Peasy
- [x] Test and Debug with Redux tools
- [x] Finalize Insertion

**Comment by ctrlplusb** [comment]
Hey @dukesx - I would challenge you to try not use Redux Forms and see how it goes. I can wholeheartedly suggest you look at something like [Formik](https://github.com/jaredpalmer/formik).

I used to be a Redux Forms user myself. However, form state is so transient (in most applications) that it completely does not make sense to store it in a global store.

I am not sure of the design of your application, but unless you don't plan on keep the form state as long lived and across multiple slices of your application I would strongly suggest not putting it in a global store (Easy Peasy or any other solution).

You could use Formik as an intermediary and then commit to global state one the form action completes.

**Comment by ctrlplusb** [comment]
Also, just want to say this sounds like an exciting project. I will keep my eye on it. Good luck!

**Comment by dukesx** [comment]
@ctrlplusb Haha thank you for your advice I would certainly take it, i completely agree! However I actually said Redux forms an integral part, like you say in normal English, I didn't mean to say Redux forms as a library or etc 😅😂

**Comment by ctrlplusb** [comment]
Ah my bad!! 😂
